### ISSUE TITLE
程序无法实现结果

### ISSUE THREAD

**Issue by annoming** [287928201/-#1]
我刚才测试的时候先输入：
            整数 气温 等于 十
           看看 气温
能得到结果十
然后又输入：
           看看  “你好”
结果还是十

**Comment by 287928201** [comment]
能够实现的只有老师给的例子，其他的实现不了。

**Comment by 287928201** [comment]
> 我刚才测试的时候先输入：
> 整体气温等于十
> 看看高温
> 能得到结果十
> 然后又输入：
> 看看“你好” 
> 结果还是十

能够实现的只有老师给的例子，其他的实现不了。
